duti -s com.google.antigravity public.plain-text all
duti -s com.google.antigravity public.data all
duti -s com.google.antigravity .md all
duti -s com.google.antigravity .conf all
duti -s com.google.antigravity .log all
duti -s com.google.antigravity .vtt all
duti -s com.google.antigravity .xml all
duti -s com.google.antigravity .html all
duti -s com.google.antigravity .css all
duti -s com.google.antigravity .js all
duti -s com.google.antigravity .ts all
duti -s com.google.antigravity .jsx all
duti -s com.google.antigravity .tsx all
duti -s com.google.antigravity .py all
duti -s com.google.antigravity .yml all
duti -s com.google.antigravity .yaml all
duti -s com.google.antigravity public.xml all
duti -s com.google.antigravity public.json all
duti -s com.google.antigravity public.yaml all
duti -s com.google.antigravity public.csv all
duti -s com.google.antigravity public.source-code all