name: Delete Previous Cloudflare Pages Deployment

on:
  workflow_call:
    inputs:
      CLOUDFLARE_API_TOKEN:
        required: true
        type: string
      CLOUDFLARE_ACCOUNT_ID:
        required: true
        type: string
      CLOUDFLARE_PROJECT_NAME:
        required: true
        type: string

jobs:
  delete-previous-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run delete_previous_deployment.py
        run: python cloudflare/delete_previous_deployment/delete_previous_deployment.py
        env:
          CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT_NAME: ${{ inputs.CLOUDFLARE_PROJECT_NAME }}